### ISSUE TITLE
Installation instructions location

### ISSUE THREAD

**Issue by anandtrex** [IGITUGraz/spore-nest-module#20]
It might be a good idea to keep all documentation (including installation instructions) part of the code so that it can be versioned with the code. The website (doxygen) could display these instructions perhaps?

**Comment by kappeld** [comment]
@mhoff and I had agreed on moving the installation guide to the wiki page such that it is kept not in the source. Since the installation process is quite complex and very much depends on the system/distribution we reasoned that this is a better strategy. In our opinion the source should just include a minimum installation guide that assumes that everything (NEST, MUSIC, MPI, ...) is already set up correctly and additionally just a list of dependencies and a minimum installation that basically shows how to build the project with cmake.

**Comment by anandtrex** [comment]
I'll leave the final decision up to you guys. But a couple of arguments in favour of keeping it with the code: if at some point we end up having different installation instructions for different versions, it would be hard to maintain in the wiki. Also, this will avoid creating a hard dependency on the Github platform. 

In principle you could have a standalone markdown/rst file in the doc folder containing the detailed installation instructions and have doxygen generate a separate html file from that i.e. the installation instructions need not necessarily be in the main README file. This doc folder could also contain all files related to generation of documentation similar to how we manage sphinx docs -- see [live-plotter](https://github.com/IGITUGraz/live-plotter) for example.  Another strategy common in unix packages is to have a INSTALL file with detailed instructions in the root directory.

**Comment by kappeld** [comment]
I prefer suggest not to put the installation guide to the Doxygen page, this seems to me the wrong place for it. The Doxygen page as it is now, is just a class reference and therefore more a developers guide than a user guide. I would find it better if we just include the guide we have now on the wiki page in README.md (my preferred option) or in a separate INSTALL.md in the root dir of SPORE (as we initially did). Any objections?

**Comment by kappeld** [comment]
Hi, can you check 612ec5189804f30513d21a17c825269f79c94a6e ?
